#!/usr/bin/env ruby
require 'rubygems'
require 'thor'
require 'pathname'

class Setup < Thor
  include Thor::Actions

  default_command :app

  #noinspection RubyMismatchedArgumentType
  source_root Pathname(__dir__).join('sources')

  desc 'app', 'Setup a new API app'
  def app
    rrx_dev
    update_base_classes
    rails
  end

  private

  def rails
    directory 'config/initializers'
  end

  def rrx_dev
    run 'bundle exec rrx_dev_setup app'
  end

  def update_base_classes
    gsub_file 'app/models/application_record.rb', /ApplicationRecord.*/, 'ApplicationRecord < RrxApi::Record'
    gsub_file 'app/controllers/application_controller.rb', /ApplicationController.*/, 'ApplicationController < RrxApi::Controller'
  end
end

Setup.start
